project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projeto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.home, name="home"),
    path('recipes/search/', views.search, name='search'),
    path('recipes/category/<int:category_id>/',
         views.category, name="category"),
    path('recipes/<int:id>/', views.recipe, name="recipe"),
]

recipes/models.py
from django.contrib.auth.models import User
from django.db import models
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(
        upload_to='recipes/covers/%Y/%m/%d/', blank=True, default='')
    # on_delete=models.SET_NULL: if category is delete set the category as Null
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True,
        default=None)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

recipes/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.http import Http404
from .models import Recipe
# For search type OR
from django.db.models import Q
# Create your views here.
from utils.pagination import make_pagination

import os


PER_PAGES = int(os.environ.get('PER_PAGE', 3))


def home(request):
    recipes = Recipe.objects.filter(is_published=True).order_by('-id')

    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGES)
    context = {
        'recipes': page_obj,
        'pagination_range': pagination_range,
    }
    return render(request, 'recipes/pages/home.html', context)


def category(request, category_id):
    recipes = get_list_or_404(
        Recipe.objects.filter(
            category__id=category_id,
            is_published=True
        ).order_by('-id')
    )

    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGES)

    context = {
        'recipes': page_obj,
        'pagination_range': pagination_range,
        'title': f'{recipes[0].category.name} - Category',
    }
    return render(request, 'recipes/pages/category.html', context)


def recipe(request, id):
    recipe = get_object_or_404(
        Recipe.objects.filter(
            pk=id,
            is_published=True
        )
    )

    context = {
        'recipe': recipe,
        'is_detail_page': True,
    }
    return render(request, 'recipes/pages/recipe-view.html', context)


def search(request):
    # strip() remove backspace
    search_term = request.GET.get('q', ' ').strip()

    if not search_term:
        raise Http404()

    recipes = Recipe.objects.filter(
        Q(
            Q(title__icontains=search_term) |
            Q(description__icontains=search_term),
        ), is_published=True
    ).order_by('-id')

    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGES)

    context = {
        'search_term': search_term,
        'search_title': f'Search for "{search_term}"',
        'pagination_range': pagination_range,
        'recipes': page_obj,
        'additional_url_query': f'&q={search_term}',
    }
    return render(request, 'recipes/pages/search.html', context)

recipes/templates/recipes/pages/category.html
{% extends "global/base.html" %}

{% block title %} {{ title }}{% endblock title %}

{% block content %}
    <div class="main-content main-content-list container">
        {% for recipe in recipes %}
            {% include "recipes/partials/recipe.html" %}
        {% endfor %}
    </div>
{% endblock content %}

recipes/templates/recipes/pages/home.html
{% extends "global/base.html" %}

{% block title %}List |{% endblock title %}

{% block content %}
    <div class="main-content main-content-list container">
        {% for recipe in recipes %}
            {% include "recipes/partials/recipe.html" %}
        {% empty %}
            <div class="center m-y">
                <h1>No recipes found here 😢</h1>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

recipes/templates/recipes/pages/recipe-view.html
{% extends "global/base.html" %}

{% block title %}{{ recipe.title }}{% endblock title %}

{% block content %}
    <div class="main-content main-content-detail container">
        {% include "recipes/partials/recipe.html" %}
    </div>
{% endblock content %}

recipes/templates/recipes/pages/search.html
{% extends "global/base.html" %}

{% block title %}{{ search_title }} |{% endblock title %}

{% block content %}
    <div class="main-content main-content-list container">
        {% for recipe in recipes %}
            {% include "recipes/partials/recipe.html" %}
        {% empty %}
            <div class="center m-y">
                <h1>No recipes found here 😢</h1>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

recipes/templates/recipes/partials/footer.html
<footer class="main-footer">
    <div class="developer">
        <a href="" target="_blank" rel="noreferrer noopener">
            By Gabriel Alcantara
        </a>
    </div>
    <div class="developer">
        <a href="" target="_blank" rel="noreferrer noopener">
            Powered by Django
        </a>
    </div>
</footer>

recipes/templates/recipes/partials/head.html
{% load static %}

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/fontawesome.min.css"
    integrity="sha512-d0olNN35C6VLiulAobxYHZiXJmq+vl+BGIgAxQtD5+kqudro/xNMvv2yIHAciGHpExsIbKX3iLg+0B6d0k4+ZA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/brands.min.css"
    integrity="sha512-8RxmFOVaKQe/xtg6lbscU9DU0IRhURWEuiI0tXevv+lXbAHfkpamD4VKFQRto9WgfOJDwOZ74c/s9Yesv3VvIQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/solid.min.css"
    integrity="sha512-pZlKGs7nEqF4zoG0egeK167l6yovsuL8ap30d07kA5AJUq+WysFlQ02DLXAmN3n0+H3JVz5ni8SJZnrOaYXWBA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

<link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">

recipes/templates/recipes/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href="{% url 'recipes:home' %}">
                <i class="fa-solid fa-utensils main-logo-icon"></i>
                <span class="main-logo-text">Recipes</span>
            </a>
        </h1>
    </div>
</header>

recipes/templates/recipes/partials/pagination.html
{% if recipes.has_other_pages %}
    <div class="container pagination">
        <div class="pagination-content">
            {% if pagination_range.first_page_out_of_range %}
                <a href="?page=1{{ additional_url_query }}" class="page-link page-item">1</a>
                <span class='page-span'>...</span>
            {% endif %}
            
            {% for page in pagination_range.pagination %}
                {% if pagination_range.current_page == page %}
                    <a href="?page={{ page }}{{ additional_url_query }}" class="page-link page-item page-current">{{ page }}</a>
                {% else %}
                    <a href="?page={{ page }}{{ additional_url_query }}" class="page-link page-item">{{ page }}</a>
                {% endif %}
            {% endfor %}

            {% if pagination_range.last_page_out_of_range %}
                <span class='page-span'>...</span>
                <a href="?page={{ pagination_range.total_pages }}{{ additional_url_query }}" class="page-link page-item">{{ pagination_range.total_pages }}</a>
            {% endif %}
        </div>
    </div>
{% endif %}

recipes/templates/recipes/partials/recipe.html
<div class="recipe recipe-list-item">
    {% if recipe.cover %}
        <div class="recipe-cover">
            <a href="{% url 'recipes:recipe' recipe.id %}">
                <img src="{{ recipe.cover.url }}" alt="temporario">
            </a>
        </div>
    {% endif %}
    <div class="recipe-title-container">
        <a href="{% url 'recipes:recipe' recipe.id %}">
            <h2 class="recipe-title">{{ recipe.title }}</h2>
        </a>
    </div>

    <div class="recipe-author">

        {% if recipe.author is not None %}
            <span class="recipe-author-item">
                <i class="fas fa-user"></i>
                {% if recipe.author.first_name %}
                    {{ recipe.author.first_name }} {{ recipe.author.last_name }}
                {% else %}
                    {{ recipe.author.username }}
                {% endif %}
            </span>
      {% endif %}
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ recipe.created_at|date:'d/m/Y' }} às {{ recipe.created_at|date:'H:i' }}
        </span>
        <span class="recipe-author-item">
            {% if recipe.category is not None %}
                <a href="{% url 'recipes:category' recipe.category.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{ recipe.category.name }}</span>
                </a>
            {% endif %}
        </span>
    </div>

    <div class="recipe-content">
        <p>{{ recipe.description }}</p>
    </div>

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">
                {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
            <div class="recipe-meta-text">
                {{ recipe.servings }} {{ recipe.servings_unit }}
            </div>
        </div>
    </div>

    {% if is_detail_page is not True %}
        <footer class="recipe-footer">
            <a href="{% url 'recipes:recipe' recipe.id %}" class="recipe-read-more button button-dark button-full-width">
                <i class="fas fa-eye"></i>
                <span>ver mais...</span>
            </a>
        </footer>
    {% endif %}

    {% if is_detail_page is True %}
        <div class="preparation-steps">
            {% if recipe.preparation_steps_is_html is True %}
                {{ recipe.preparation_steps|safe }}
            {% else %}
                {{ recipe.preparation_steps|linebreaksbr }}
            {% endif %}
        </div>
    {% endif %}
</div>

recipes/templates/recipes/partials/search.html
<div class="search-container">
    <div class="container">
        <form action="{% url 'recipes:search' %}" method='GET' class="search-form">
            <input type="search" class="search-input" value='{{ search_term }}' name="q">
            <button type="submit" class="search-button"><i class="fa-solid fa-magnifying-glass"></i></button>
        </form>
    </div>
</div>